language: python
# services:
  # - go
  # - singularity
python:
  # - "2.7"
  # - "3.4"
  - "3.5"
  - "3.7"
  
cache:
  directories: 
    - $HOME/.pip
    - $HOME/.singularity
    - /opt/singularity
    # - $HOME/virtualenv ### too big

before_install:
  - sudo apt-get update 
  - sudo apt-get install -y graphviz
  - echo pass
  - pip install 'spiper@https://github.com/shouldsee/spiper/tarball/0.0.6'
  - python -V
  - pip install .
script:
  - bash run.sh python

